FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src

COPY Relevantz.SOR.Common/Relevantz.SOR.Common.csproj Relevantz.SOR.Common/
COPY Relevantz.SOR.Core/Relevantz.SOR.Core.csproj Relevantz.SOR.Core/
COPY Relevantz.SOR.Data/Relevantz.SOR.Data.csproj Relevantz.SOR.Data/
COPY Relevantz.SOR.Api/Relevantz.SOR.Api.csproj Relevantz.SOR.Api/

RUN dotnet restore Relevantz.SOR.Api/Relevantz.SOR.Api.csproj

COPY . .

WORKDIR /src/Relevantz.SOR.Api
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 5116
ENTRYPOINT ["dotnet", "Relevantz.SOR.Api.dll"]
