// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relevantz.SOR.Data.DBContexts;

#nullable disable

namespace Relevantz.SOR.Data.Migrations
{
    [DbContext(typeof(SORDbContext))]
    [Migration("20260227101134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.ApprovalChain", b =>
                {
                    b.Property<int>("ApprovalChainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApprovalChainId"));

                    b.Property<string>("ChainName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ApprovalChainId");

                    b.ToTable("ApprovalChains");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.ApprovalChainStep", b =>
                {
                    b.Property<int>("ApprovalChainStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApprovalChainStepId"));

                    b.Property<int>("ApprovalChainId")
                        .HasColumnType("int");

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("ApprovalChainStepId");

                    b.HasIndex("ApprovalChainId");

                    b.ToTable("ApprovalChainSteps");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.HasIndex("OfferId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.FinanceBudget", b =>
                {
                    b.Property<int>("FinanceBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FinanceBudgetId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("UsedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FinanceBudgetId");

                    b.ToTable("FinanceBudgets");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.FullTimeDetails", b =>
                {
                    b.Property<int>("FullTimeDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FullTimeDetailsId"));

                    b.Property<decimal>("Allowances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnnualCtc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("BackgroundVerificationRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BonusOrVariablePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConfirmationTerms")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("EsopDetails")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("GratuityEligibility")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Hra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InsurancePlan")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("JoiningBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LeaveEntitlement")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("NonCompeteEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NoticePeriod")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<string>("OtherBenefits")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("PfEligibility")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProbationPeriod")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FullTimeDetailsId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.ToTable("FullTimeDetails");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.InternshipDetails", b =>
                {
                    b.Property<int>("InternshipDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InternshipDetailsId"));

                    b.Property<bool>("AccommodationAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("AccommodationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BreakageCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CertificateRetentionTerms")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<decimal?>("FullTimeSalaryAfterInternship")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InsuranceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("InsuranceEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("InternshipEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InternshipStartDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("JoiningBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<string>("OtherBenefits")
                        .HasColumnType("longtext");

                    b.Property<string>("PayFrequency")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PaymentTiming")
                        .HasColumnType("longtext");

                    b.Property<string>("RequiredDocuments")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("RetentionBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ServiceAgreementDurationMonths")
                        .HasColumnType("int");

                    b.Property<string>("ServiceAgreementPeriod")
                        .HasColumnType("longtext");

                    b.Property<decimal>("StipendAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrainingDuration")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingInstitution")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingWorkingDays")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("InternshipDetailsId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.ToTable("InternshipDetails");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OfferId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OfferNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ParentOfferId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OfferId");

                    b.HasIndex("CandidateId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferCommonDetails", b =>
                {
                    b.Property<int>("OfferCommonDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OfferCommonDetailsId"));

                    b.Property<string>("CandidateAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CandidatePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CompanyPolicyText")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("ConfidentialityClause")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HrContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HrEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HrPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OfferIssueDate")
                        .HasColumnType("date");

                    b.Property<string>("ReportingManager")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SignatoryDesignation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SignatoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SignatorySignatureImagePath")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("WeeklyHours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("WorkLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OfferCommonDetailsId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.ToTable("OfferCommonDetails");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferTemplate", b =>
                {
                    b.Property<int>("OfferTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OfferTemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OfferTemplateId");

                    b.ToTable("OfferTemplates");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferVersion", b =>
                {
                    b.Property<int>("OfferVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OfferVersionId"));

                    b.Property<DateTime>("ArchivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("ArchivedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusAtVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("OfferVersionId");

                    b.HasIndex("OfferId");

                    b.ToTable("OfferVersions");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferWorkflow", b =>
                {
                    b.Property<int>("OfferWorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OfferWorkflowId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WorkflowNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("OfferWorkflowId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.ToTable("OfferWorkflows");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferWorkflowStep", b =>
                {
                    b.Property<int>("OfferWorkflowStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OfferWorkflowStepId"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OfferWorkflowId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SkipJustification")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OfferWorkflowStepId");

                    b.HasIndex("OfferWorkflowId");

                    b.ToTable("OfferWorkflowSteps");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.ApprovalChainStep", b =>
                {
                    b.HasOne("Relevantz.SOR.Common.Entities.ApprovalChain", "ApprovalChain")
                        .WithMany("Steps")
                        .HasForeignKey("ApprovalChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalChain");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.AuditLog", b =>
                {
                    b.HasOne("Relevantz.SOR.Common.Entities.Offer", "Offer")
                        .WithMany("AuditLogs")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.FullTimeDetails", b =>
                {
                    b.HasOne("Relevantz.SOR.Common.Entities.Offer", "Offer")
                        .WithOne("FullTimeDetails")
                        .HasForeignKey("Relevantz.SOR.Common.Entities.FullTimeDetails", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.InternshipDetails", b =>
                {
                    b.HasOne("Relevantz.SOR.Common.Entities.Offer", "Offer")
                        .WithOne("InternshipDetails")
                        .HasForeignKey("Relevantz.SOR.Common.Entities.InternshipDetails", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.Offer", b =>
                {
                    b.HasOne("Relevantz.SOR.Common.Entities.Candidate", "Candidate")
                        .WithMany("Offers")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferCommonDetails", b =>
                {
                    b.HasOne("Relevantz.SOR.Common.Entities.Offer", "Offer")
                        .WithOne("OfferCommonDetails")
                        .HasForeignKey("Relevantz.SOR.Common.Entities.OfferCommonDetails", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferVersion", b =>
                {
                    b.HasOne("Relevantz.SOR.Common.Entities.Offer", "Offer")
                        .WithMany("OfferVersions")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferWorkflow", b =>
                {
                    b.HasOne("Relevantz.SOR.Common.Entities.Offer", "Offer")
                        .WithOne("OfferWorkflow")
                        .HasForeignKey("Relevantz.SOR.Common.Entities.OfferWorkflow", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferWorkflowStep", b =>
                {
                    b.HasOne("Relevantz.SOR.Common.Entities.OfferWorkflow", "OfferWorkflow")
                        .WithMany("Steps")
                        .HasForeignKey("OfferWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferWorkflow");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.ApprovalChain", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.Candidate", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.Offer", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("FullTimeDetails");

                    b.Navigation("InternshipDetails");

                    b.Navigation("OfferCommonDetails");

                    b.Navigation("OfferVersions");

                    b.Navigation("OfferWorkflow");
                });

            modelBuilder.Entity("Relevantz.SOR.Common.Entities.OfferWorkflow", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
